Finished ticket #11
blameaimer/NC-backend pull request #10
Opened 2022-02-15 16:24 UTC by blameaimer

-Creating test case for the new end point
-Creating end-point
-Creating and testing functions
-Considering errors
-Creating 404 test cases
-Handling the error

2022-02-15 16:41 UTC, emilyb93 requested changes
Some notes about the response here but otherwise looks good :)

2022-02-15 16:41 UTC, emilyb93 commented on __tests__/app.test.js
> +        body: 'GOAT never seen a better article'
I would like to see this respond with the comment_id also to prove it has been added to the database correctly

2022-02-15 16:41 UTC, emilyb93 commented on errors/index.js
> +    }
I would say if something is invalid, that is a bad request and should be a 400, or you need to amend your error message as 404 is reserved for valid queries that are not found

2022-02-16 11:04 UTC, maddierosecodes approved these changes
All changes addressed :)

2022-02-16 11:05 UTC, merged